"""
=============================================================================
FILE: server/blog_generator/migrations/0001_initial.py
PURPOSE: The first (and currently only) database migration for the
         blog_generator app. This file tells Django exactly how to create
         the 'blog_generator_blogpost' table in the database.
=============================================================================

HOW IT WORKS:
- Django's migration system tracks database schema changes over time, similar
  to how Git tracks code changes. Each migration file is a snapshot of a
  change to the schema.
- This file was AUTO-GENERATED by running `python manage.py makemigrations`
  after the BlogPost model was first written in models.py. You should
  NEVER edit migration files by hand unless you know exactly what you're doing.
- When you run `python manage.py migrate`, Django looks at this file and
  executes the operations inside it to create the actual SQL table.
- The `initial = True` flag marks this as the very first migration for the app.
- The `dependencies` list ensures Django's built-in auth tables (which hold
  the User model) are created BEFORE this table, since BlogPost has a
  ForeignKey to User and the foreign key constraint requires the parent
  table to exist first.

WHAT THIS MIGRATION CREATES:
  Table: blog_generator_blogpost
  Columns:
    id              → Auto-incrementing integer primary key (BigAutoField)
    user_id         → Foreign key integer linking to auth_user.id
    youtube_title   → VARCHAR(300) — the video title
    youtube_link    → VARCHAR(200) — the source URL
    generated_content → TEXT — the full AI-written article
    created_at      → DATETIME — set automatically on INSERT

REGENERATING MIGRATIONS:
  If you change models.py (e.g., add a new field), run:
    python manage.py makemigrations
  Django will create a new numbered file (0002_...) describing just the diff.
=============================================================================
"""
# Generated by Django 6.0.2 on 2026-02-28 09:49


import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_title', models.CharField(max_length=300)),
                ('youtube_link', models.URLField()),
                ('generated_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
