# Generated by Django 6.0.2 on 2026-04-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_generator', '0002_taskprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
