"""
-----------------------------------------------------------------------------
FILE: server/blog_generator/models.py
PURPOSE: Defines the data structure (schema) for the database.
AUTHORS: ContentFlow Development Team
-----------------------------------------------------------------------------
"""
from django.db import models

from django.contrib.auth.models import User

# --- DATA STORAGE SCHEMA ---

class BlogPost(models.Model):
    """
    The core model representing a generated article.
    Each record maps directly to a specific user and contains the 
    result of the 'Video -> Audio -> Text -> Synthesis' pipeline.
    """
    
    # Linked to Django's built-in User model. 
    # If a user is deleted, their articles are cascade deleted (on_delete=models.CASCADE).
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    # Metadata extracted from the YouTube video stream.
    youtube_title = models.CharField(max_length=300)
    youtube_link = models.URLField()
    
    # The final Markdown/HTML content generated by the AI synthesis engine.
    generated_content = models.TextField()
    
    # Automatic timestamp for organization and sorting in the 'My Articles' list.
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """String representation of the object (used in the Django Admin panel)."""
        return f"{self.youtube_title} | Created by {self.user.username}"

class TaskProgress(models.Model):
    """
    Tracks the real-time status of a background generation task.
    This model is used to communicate progress between the Celery/Django-Q 
    worker and the frontend UI polling mechanism.
    """
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('RUNNING', 'Running'),
        ('COMPLETED', 'Completed'),
        ('FAILED', 'Failed'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task_id = models.CharField(max_length=255, unique=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='PENDING')
    message = models.TextField(blank=True)
    progress = models.IntegerField(default=0) # 0 to 100
    blog_post = models.ForeignKey(BlogPost, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Task {self.task_id} | {self.status} ({self.progress}%)"