"""
=============================================================================
FILE: server/blog_generator/models.py
PURPOSE: Defines the data structure (schema) for the database. Every table
         that the application uses is defined here as a Python class that
         inherits from Django's Model base class.
=============================================================================

HOW IT WORKS:
- Django's ORM (Object-Relational Mapper) translates these Python classes
  into actual SQL table definitions. You never write raw SQL — Django does
  it for you.
- When you run `python manage.py makemigrations`, Django inspects this file
  and generates migration files that describe the changes.
- When you run `python manage.py migrate`, Django executes those migrations
  and actually creates or alters the database tables.

MODEL DEFINED: BlogPost
  This is the only table in the application. Each row represents one
  AI-generated article that a specific user has created.

  Fields:
    user            → ForeignKey to Django's built-in User model.
                      on_delete=CASCADE means if a user account is deleted,
                      all their articles are automatically deleted too.
    youtube_title   → The title of the original YouTube video, extracted by
                      yt-dlp and stored for display in the article list.
    youtube_link    → The original URL, stored so users can navigate back to
                      the source video from the article detail page.
    generated_content → The full AI-written article text (Markdown format),
                      stored as unlimited-length text (TextField).
    created_at      → Timestamp automatically set to the moment the row is
                      created (auto_now_add=True). Used for sorting the archive
                      newest-first and displaying "Processed: Apr 25, 2026".

TOOLS & PATTERNS:
  - Django ORM: Python-based database abstraction, works with SQLite
    (development) and PostgreSQL (production) without code changes.
  - ForeignKey: Creates a many-to-one relationship — one User can have many
    BlogPosts, but each BlogPost belongs to exactly one User.
  - auto_now_add: A Django field option that sets the datetime automatically
    on INSERT and makes it read-only thereafter.
=============================================================================
"""
from django.db import models

from django.contrib.auth.models import User

# ── DATA STORAGE SCHEMA ──

class BlogPost(models.Model):
    """
    The core model representing a generated article.
    Each record maps directly to a specific user and contains the 
    result of the 'Video -> Audio -> Text -> Synthesis' pipeline.
    """
    
    # Linked to Django's built-in User model. 
    # If a user is deleted, their articles are cascade deleted (on_delete=models.CASCADE).
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    # Metadata extracted from the YouTube video stream.
    youtube_title = models.CharField(max_length=300)
    youtube_link = models.URLField()
    
    # The final Markdown/HTML content generated by the AI synthesis engine.
    generated_content = models.TextField()
    
    # Automatic timestamp for organization and sorting in the 'My Articles' list.
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """String representation of the object (used in the Django Admin panel)."""
        return f"{self.youtube_title} | Created by {self.user.username}"

class TaskProgress(models.Model):
    """
    Tracks the real-time status of a background generation task.
    This model is used to communicate progress between the Celery/Django-Q 
    worker and the frontend UI polling mechanism.
    """
    STATUS_CHOICES = [
        ('PENDING', 'Pending'),
        ('RUNNING', 'Running'),
        ('COMPLETED', 'Completed'),
        ('FAILED', 'Failed'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task_id = models.CharField(max_length=255, unique=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='PENDING')
    message = models.TextField(blank=True)
    progress = models.IntegerField(default=0) # 0 to 100
    blog_post = models.ForeignKey(BlogPost, on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Task {self.task_id} | {self.status} ({self.progress}%)"