from django.db import models
from django.contrib.auth.models import User

# ── DATA STORAGE SCHEMA ──

class BlogPost(models.Model):
    """
    The core model representing a generated article.
    Each record maps directly to a specific user and contains the 
    result of the 'Video -> Audio -> Text -> Synthesis' pipeline.
    """
    
    # Linked to Django's built-in User model. 
    # If a user is deleted, their articles are cascade deleted (on_delete=models.CASCADE).
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    # Metadata extracted from the YouTube video stream.
    youtube_title = models.CharField(max_length=300)
    youtube_link = models.URLField()
    
    # The final Markdown/HTML content generated by the AI synthesis engine.
    generated_content = models.TextField()
    
    # Automatic timestamp for organization and sorting in the 'My Articles' list.
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """String representation of the object (used in the Django Admin panel)."""
        return f"{self.youtube_title} | Created by {self.user.username}"